### ISSUE TITLE
TypeError: Cannot read property 'started_at' of undefined

### ISSUE THREAD

**Issue by HeatfanJohn** [Automatic/tripviewer#6]
I'm running a local copy of this `tripviewer` application on a Nextthing Co. CHIP computer and today when I tried to access the application I received the error shown in the title of this issue.  The stack for the error is displayed below.
```
TypeError: Cannot read property 'started_at' of undefined
    at /home/chip/tripviewer/libs/helpers.js:34:24
    at _.pluck._.map.sort.a (/home/chip/tripviewer/node_modules/underscore/underscore.js:380:19)
    at Function._.map._.collect (/home/chip/tripviewer/node_modules/underscore/underscore.js:172:24)
    at Function._.sortBy (/home/chip/tripviewer/node_modules/underscore/underscore.js:376:22)
    at Object.exports.sortByDate (/home/chip/tripviewer/libs/helpers.js:33:12)
    at filterAndSendTrips (/home/chip/tripviewer/routes/api.js:17:27)
    at /home/chip/tripviewer/routes/api.js:59:5
    at /home/chip/tripviewer/node_modules/async/dist/async.js:847:20
    at /home/chip/tripviewer/node_modules/async/dist/async.js:4909:22
    at /home/chip/tripviewer/node_modules/async/dist/async.js:339:31
[09:45:46] [nodemon] app crashed - waiting for file changes before starting...
```
In debugging this problem it appears that no results are being returned in function `downloadAllTrips`.

Has anything changed recently in the Automatic API that is causing this problem?

**Comment by HeatfanJohn** [comment]
As of 1:45 PM EST this error is no longer happening.  This must have been caused by an Automatic API issue that is now resolved.

However, in debugging this I got tired of having this application redirect back to `http://localhost` so I updated `app.js` to include `callbackURL: "/"` in the `AutomaticStrategy` so that my website name and TCP port would be included in the callback to my site.
```
// Use the AutomaticStrategy within Passport
passport.use(new AutomaticStrategy({
  clientID: nconf.get('AUTOMATIC_CLIENT_ID'),
  clientSecret: nconf.get('AUTOMATIC_CLIENT_SECRET'),
  scope: ['scope:trip', 'scope:location', 'scope:vehicle:profile', 'scope:vehicle:events', 'scope:behavior'],
  callbackURL: "/"
},
  function(accessToken, refreshToken, profile, done) {
    profile.accessToken = accessToken;
    return done(null, profile);
  }
));

```

However, this causes Automatic to display `Error: invalid_request` when `&redirect_uri=` is included in the  `https://accounts.automatic.com/oauth/authorize?response_type=code&redirect_uri=` URL.

Can someone tell me where I can report that issue to Automatic?

**Comment by maroux** [comment]
Hi @HeatfanJohn 

Thanks for reporting the issue - I'm not sure why you ran into this problem, but I'll keep an eye out for errors like this.

Your second problem is because the `redirect_uri` is validated per OAuth2 spec. This means it has to be exactly same as what's provided in your app definition when you created it on developer.automatic.com. In the future, we may expand that to be able to use multiple values to make this more useful for local testing.

Thanks!

**Comment by HeatfanJohn** [comment]
Hi @maroux 

Thank you for the telling me how to correct my `redirect_uri` problem.  I updated my application's configuration on the Automatic site to specify the correct callback URI.

BTW, I developed this pull request https://github.com/Automatic/tripviewer/pull/7 to prevent this `TypeError` issue.

**Comment by HeatfanJohn** [comment]
Hello @maroux @brendannee,

I've done more debugging on this to see the source of my issues with the Automatic API as used by this tripviewer app.  From my debugging it appears that the source of the issue is that this tripviewer application does not use the `Accept-Encoding: gzip` header and when the Automatic `api/trip` API is called with a limit of 250 for my account which has over 400 trips, the first page of the response from Automatic is "truncated" and does not contain the correct number of closing braces (`}`) and a closing square bracket. 

This causes the API response to be treated as a string by Javascript instead of being converted from JSON to a Javascript object.

I can replicate this behavior using `curl` taking the `Authorization` header from an authenticated request and using it in my test `curl` command.  If I perform a `curl` request on my account of:

`curl -o out.txt "https://api.automatic.com/trip/?started_at__gte=1363071600&started_at__lte=1483938000&limit=250" --header "Authorization:bearer xxx" --verbose`

I get:

```
{"_metadata":{"count":312,"next":"https://api.automatic.com/trip/?started_at__gte=1363071600&cursor=dd48015f-6aed-443b-9
c3f-c6aa873e793d&started_at__lte=1483938000&limit=250&page=2","previous":null},"results":[{"id":
.
.
.
ATuATwAR}BXuALi@DiBLkBJuADiBBkBB}DDyB@cBBkJHgDD{@@eHFgPNgf@f@ya@^i@@[QCAwFK}EIeEIWAQAc@E[Ec
```

If I do the same request containing the `Accept-Encoding: gzip` header and then `gzip -d` the result I get:

```
{"_metadata":{"count":312,"next":"https://api.automatic.com/trip/?started_at__gte=1363071600&cursor=17bfd377-b808-4b31-b
256-e4a54b36718f&started_at__lte=1483938000&limit=250&page=2","previous":null},"results":[{"id":
.
.
.
,"idling_time_s":150,"user":"https://api.automatic.com/user/U_2b78417cxxxxxxxx/"}]}

```

The workaround for this in `tripviewer` would be to add the `gzip` header and un-gzip the response before processing it.  I'm not looking into how to implement that.
